# Generated by Django 3.2.2 on 2021-05-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210510_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutmyskills',
            options={'verbose_name': 'About My Skills', 'verbose_name_plural': 'About My Skills'},
        ),
        migrations.AddField(
            model_name='aboutmyskills',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.skills'),
            preserve_default=False,
        ),
    ]
