# Generated by Django 3.2.2 on 2021-05-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210510_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.RemoveField(
            model_name='aboutmyskills',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Myself',
        ),
        migrations.DeleteModel(
            name='AboutMySkills',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
