# Generated by Django 3.2.2 on 2021-05-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210517_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
                ('title', models.CharField(max_length=100)),
                ('paragraph', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Accomplishment',
                'verbose_name_plural': 'Accomplishments',
            },
        ),
    ]
